import { db, ws, json, error } from '@appdeploy/sdk';
const SUBSCRIPTIONS_TABLE='entity_subscriptions';
export type SubscriptionRecord={id:string;entity_type:string;entity_id:string;connection_id:string;created_at:number};
async function listSubscriptions(){const{items}=await db.list(SUBSCRIPTIONS_TABLE,{limit:1000});return items as SubscriptionRecord[]}
export async function removeSubscriptionsByConnection(connectionId:string){const items=await listSubscriptions();const ids=items.filter(i=>i.connection_id===connectionId).map(i=>i.id);if(ids.length)await db.delete(SUBSCRIPTIONS_TABLE,ids)}
export async function addSubscription(entityType:string,entityId:string,connectionId:string){await db.add(SUBSCRIPTIONS_TABLE,[{entity_type:entityType,entity_id:entityId,connection_id:connectionId,created_at:Date.now()}])}
export async function removeSubscriptions(entityType:string,entityId:string,connectionId:string){const items=await listSubscriptions();const ids=items.filter(i=>i.entity_type===entityType&&i.entity_id===entityId&&i.connection_id===connectionId).map(i=>i.id);if(ids.length)await db.delete(SUBSCRIPTIONS_TABLE,ids)}
export async function notifySubscribers(entityType:string,entityId:string,payload:unknown,excludeConnectionId?:string){const items=await listSubscriptions();const ids=Array.from(new Set(items.filter(i=>i.entity_type===entityType&&i.entity_id===entityId).map(i=>i.connection_id).filter(id=>id!==excludeConnectionId)));if(!ids.length)return;await ws.send(ids,{v:1,type:'entity.update',payload:{entity_type:entityType,entity_id:entityId,data:payload}})}
export const realtimeSubscriptionRoutes={'POST /api/subscriptions':[async({body}:{body:any})=>{const{entity_type,entity_id,connection_id}=body||{};if(!entity_type||!entity_id||!connection_id)return error('entity_type, entity_id, connection_id are required');await addSubscription(entity_type,entity_id,connection_id);return json({ok:true})}], 'POST /api/subscriptions/remove':[async({body}:{body:any})=>{const{entity_type,entity_id,connection_id}=body||{};if(!entity_type||!entity_id||!connection_id)return error('entity_type, entity_id, connection_id are required');await removeSubscriptions(entity_type,entity_id,connection_id);return json({ok:true})}]};
