import { useEffect, useState } from 'react';
import { Plus, Target, Wallet, Shield, Scale, ArrowRightLeft, Trophy, ChevronRight, X, LogIn, LogOut, Sparkles, Archive, Repeat2, Check, CircleDollarSign, CalendarDays, Pause, Play, MoreHorizontal } from 'lucide-react';
import type { Goal, Commitment, Event, State, User } from '../shared/types';
import type { QuestLedgerClient } from './client';
import { errorMessage, authErrorCopy } from './client';
import { AppDeployClient } from './client.appdeploy';

// The only line that names an implementation. Step 7 swaps this for the HTTP
// client; nothing else in this file changes.
const client: QuestLedgerClient = new AppDeployClient();

const empty: State = { goals: [], accounts: [], buckets: [], commitments: [], events: [], xp: 0, unallocated: 0, stats: { integrity: 100, discipline: 0, consistency: 0, balance: 50, power: 0, adaptability: 0 } };
const money = (n: number) => `KSh ${Math.round(n).toLocaleString()}`;
const dateText = (v?: string) => v ? new Date(v).toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' }) : '—';
const statusFor = (c: Commitment) => !c.active ? 'Paused' : Number(c.balance || 0) >= Number(c.amount) ? 'Fully funded' : Number(c.balance || 0) > 0 ? 'Partially funded' : 'Underfunded';
const cyclesText = (c: Commitment) => { const amount = Number(c.amount || 0), balance = Number(c.balance || 0); if (!amount) return '0 cycles'; const full = Math.floor(balance / amount), remainder = Math.round(balance % amount); return full ? `${full} full ${c.frequency}${full === 1 ? '' : 's'}${remainder ? ` + ${money(remainder)}` : ''}` : `0 full cycles + ${money(remainder)}`; };
const exhaustionText = (c: Commitment) => { const amount = Number(c.amount || 0), balance = Number(c.balance || 0); if (!c.nextDueAt || amount <= 0 || balance <= 0) return 'Needs funding'; const full = Math.floor(balance / amount); const d = new Date(c.nextDueAt); if (balance % amount === 0 && full > 0) d.setDate(d.getDate() + Math.max(0, full - 1) * (c.frequency === 'daily' ? 1 : c.frequency === 'weekly' ? 7 : c.frequency === 'monthly' ? 30 : 365)); return dateText(d.toISOString()); };

export default function App() {
  const [user, setUser] = useState<User>(null), [checking, setChecking] = useState(true), [state, setState] = useState(empty);
  const [tab, setTab] = useState('home'), [modal, setModal] = useState<string | null>(null), [form, setForm] = useState<Record<string, string>>({});
  const [busy, setBusy] = useState(false), [error, setError] = useState('');
  useEffect(() => { client.getUser().then(setUser).catch(() => setUser(null)).finally(() => setChecking(false)); }, []);
  const login = async () => { setError(''); try { const r = await client.signIn(); setUser(r.user); } catch (e) { setError(authErrorCopy(e)); } };
  const logout = () => { setUser(null); setState(empty); client.signOut().catch(() => {}); };
  const load = async () => { const r = await client.get<State>('/api/state'); setState(r.data); };
  useEffect(() => { if (user) load().catch(() => setError('Could not load your private data.')); }, [user]);
  const mutate = async (path: string, body: Record<string, unknown>) => { setBusy(true); setError(''); try { await client.post(path, body); await load(); setModal(null); setForm({}); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } };
  const xpLevel = Math.max(1, Math.floor(state.xp / 500) + 1), xpIn = state.xp % 500;
  const goalAllocated = state.goals.filter(g => !g.commitmentId && g.status !== 'archived').reduce((s, g) => s + g.saved, 0);
  const commitmentReserved = state.commitments.reduce((s, c) => s + Number(c.balance || 0), 0);
  const totalMoney = state.unallocated + goalAllocated + commitmentReserved;
  const activeGoals = state.goals.filter(g => !g.commitmentId && (g.status === 'active' || g.status === 'completed'));
  const archives = state.goals.filter(g => g.status === 'archived' && !g.commitmentId);
  const create = () => mutate('/api/goals', { name: form.name, target: Number(form.target), bucket: form.bucket, account: form.account, deadline: form.deadline || undefined, kind: form.kind || 'goal' });
  const allocate = () => mutate('/api/contributions', { goalId: form.goalId, amount: Number(form.amount) });
  const addMoney = () => mutate('/api/money', { amount: Number(form.amount), location: form.location || '' });
  const adjust = () => mutate('/api/rebalance', { kind: form.kind || 'transfer', from: form.from, to: form.to, amount: Number(form.amount), reason: form.reason || '' });
  const complete = (g: Goal) => mutate('/api/complete', { goalId: g.id });
  const spend = (g: Goal, amount?: number) => mutate('/api/spend', { goalId: g.id, amount: amount || g.saved, reason: form.reason || '' });
  const createCommitment = () => mutate('/api/commitments', { name: form.name, amount: Number(form.amount), frequency: form.frequency, dueDay: Number(form.dueDay || 1), kind: form.kind || 'expense', bucket: form.bucket, account: form.account });
  const commitmentAction = (path: string) => mutate(path, { id: form.commitmentId, amount: Number(form.amount), reason: form.reason || '', to: form.to });
  if (checking) return <div className='splash'><div className='crest'>Q</div><b>QuestLedger</b><span>Loading your financial world…</span></div>;
  if (!user) return <Landing onLogin={login} error={error} />;
  const nav = [['home', 'Dashboard'], ['goals', 'Quests'], ['commitments', 'Recurring'], ['archive', 'Archives'], ['stats', 'Character'], ['analysis', 'Analytics']];
  return <div className='shell'>
    <header><div className='brand'><div className='crest'>Q</div><div><b>QuestLedger</b><span>Your financial RPG</span></div></div><div className='userBar'><span>{user.name || user.email || 'Player'}</span><div className='level'><b>LEVEL {xpLevel}</b><div className='xp'><i style={{ width: `${xpIn / 5}%` }} /></div><small>{xpIn}/500 XP</small></div><button className='iconBtn' onClick={logout}><LogOut /></button></div></header>
    <main>{error && <div className='errorBanner'>{error}<button onClick={() => setError('')}>×</button></div>}
      {tab === 'home' && <Dashboard state={state} total={totalMoney} goalAllocated={goalAllocated} open={g => setModal('detail:' + g.id)} newGoal={() => { setForm({}); setModal('goal'); }} add={() => { setForm({}); setModal('money'); }} allocate={() => { setForm({}); setModal('contribute'); }} adjust={() => { setForm({}); setModal('rebalance'); }} />}
      {tab === 'goals' && <Goals goals={activeGoals} open={g => setModal('detail:' + g.id)} newGoal={() => { setForm({}); setModal('goal'); }} allocate={g => { setForm({ goalId: g.id }); setModal('contribute'); }} complete={complete} spend={g => { setForm({ goalId: g.id }); setModal('spend:' + g.id); }} />}
      {tab === 'commitments' && <Commitments commitments={state.commitments.filter(c => !c.archived)} newCommitment={() => { setForm({}); setModal('commitment'); }} open={c => { setForm({ commitmentId: c.id }); setModal('commitmentDetail'); }} toggle={c => mutate('/api/commitments/toggle', { id: c.id, active: !c.active })} />}
      {tab === 'archive' && <Archives goals={archives} commitments={state.commitments.filter(c => c.archived)} open={g => setModal('detail:' + g.id)} />}
      {tab === 'stats' && <Character state={state} />}
      {tab === 'analysis' && <Analytics state={state} addBucket={() => { setForm({}); setModal('bucket'); }} addAccount={() => { setForm({}); setModal('account'); }} />}
    </main>
    <nav>{nav.map(([id, label]) => <button className={tab === id ? 'active' : ''} onClick={() => setTab(id)} key={id}>{id === 'home' ? <Target /> : id === 'goals' ? <Trophy /> : id === 'commitments' ? <Repeat2 /> : id === 'archive' ? <Archive /> : id === 'stats' ? <Shield /> : <Scale />}<span>{label}</span></button>)}</nav>
    {modal?.startsWith('detail:') ? <GoalDetail goal={state.goals.find(g => g.id === modal.slice(7))} events={state.events} close={() => setModal(null)} edit={g => { setForm({ id: g.id, name: g.name, bucket: g.bucket, account: g.account || '', deadline: g.deadline || '', kind: g.kind }); setModal('goalEdit'); }} adjustTarget={g => { setForm({ id: g.id, target: String(g.target), releaseTo: 'unallocated' }); setModal('goalTarget'); }} archive={g => { setForm({ id: g.id, releaseTo: 'unallocated' }); setModal('goalArchive'); }} allocate={g => { setForm({ goalId: g.id }); setModal('contribute'); }} spend={g => { setForm({ goalId: g.id }); setModal('spend:' + g.id); }} />
      : modal?.startsWith('spend:') ? <Modal title='Mark money as spent' close={() => setModal(null)}><Form modal='spend' form={form} setForm={setForm} state={state} submit={() => spend(state.goals.find(g => g.id === modal.slice(6))!, Number(form.amount))} busy={busy} /></Modal>
      : modal === 'commitmentDetail' ? <CommitmentDetail commitment={state.commitments.find(c => c.id === form.commitmentId)} goals={state.goals} events={state.events} close={() => setModal(null)} openModal={m => setModal(m)} edit={c => { setForm({ id: c.id, name: c.name, bucket: c.bucket, account: c.account || '', kind: c.kind }); setModal('commitmentEdit'); }} archive={c => { setForm({ commitmentId: c.id }); setModal('commitmentArchive'); }} toggle={c => mutate('/api/commitments/toggle', { id: c.id, active: !c.active })} />
      : modal && <Modal title={modal === 'goal' ? 'New Quest' : modal === 'goalEdit' ? 'Edit Quest' : modal === 'goalTarget' ? 'Adjust Quest Target' : modal === 'goalArchive' ? 'Archive Quest' : modal === 'money' ? 'Add Unallocated Money' : modal === 'contribute' ? 'Allocate Money' : modal === 'rebalance' ? 'Adjust Allocation' : modal === 'commitment' ? 'New Recurring Commitment' : modal === 'commitmentEdit' ? 'Edit Commitment' : modal === 'account' ? 'Add Account' : 'Add Bucket'} close={() => setModal(null)}><Form modal={modal} form={form} setForm={setForm} state={state} submit={modal === 'goal' ? create : modal === 'goalEdit' ? () => mutate('/api/goals/update', form) : modal === 'goalTarget' ? () => mutate('/api/goals/adjust-target', { id: form.id, target: Number(form.target), releaseTo: form.releaseTo }) : modal === 'goalArchive' ? () => mutate('/api/goals/archive', { id: form.id, releaseTo: form.releaseTo }) : modal === 'money' ? addMoney : modal === 'contribute' ? allocate : modal === 'rebalance' ? adjust : modal === 'commitment' ? createCommitment : modal === 'commitmentEdit' ? () => mutate('/api/commitments/update', { id: form.id, name: form.name, bucket: form.bucket, account: form.account, kind: form.kind }) : v => mutate(modal === 'account' ? '/api/accounts' : '/api/buckets', { name: v?.name })} busy={busy} /></Modal>}
    {['commitmentTopup','commitmentSpend','commitmentRebalance','commitmentAdjust'].includes(modal || '') && <Modal title={modal === 'commitmentTopup' ? 'Top up commitment' : modal === 'commitmentSpend' ? 'Mark commitment money spent' : modal === 'commitmentRebalance' ? 'Rebalance commitment' : 'Adjust commitment'} close={() => setModal(null)}><Form modal={modal!} form={form} setForm={setForm} state={state} submit={() => commitmentAction(modal === 'commitmentTopup' ? '/api/commitments/topup' : modal === 'commitmentSpend' ? '/api/commitments/spend' : modal === 'commitmentRebalance' ? '/api/commitments/rebalance' : '/api/commitments/adjust')} busy={busy} /></Modal>}
    {modal === 'commitmentArchive' && <Modal title='Archive commitment' close={() => setModal(null)}><Form modal='commitmentArchive' form={form} setForm={setForm} state={state} submit={() => mutate('/api/commitments/archive', { id: form.commitmentId })} busy={busy} /></Modal>}
  </div>;
}

function Landing({ onLogin, error }: { onLogin: () => void; error: string }) { return <div className='landing'><header className='landingHeader'><div className='brand'><div className='crest'>Q</div><div><b>QuestLedger</b><span>Your financial RPG</span></div></div><button className='ghostBtn' onClick={onLogin}><LogIn /> Sign in</button></header><main className='landingMain'><section className='landingHero'><div className='heroCopy'><div className='pill'><Sparkles /> FINANCIAL PROGRESS, MADE VISIBLE</div><h1>Give your money a <em>mission.</em></h1><p>Know what you have, what is allocated, what still needs funding, and what has already been spent.</p><div className='heroActions'><button className='primary big' onClick={onLogin}>Start your journey <ChevronRight /></button><span>No bank connection required.</span></div>{error && <div className='landingError'>{error}</div>}</div><div className='characterPreview'><div className='previewTop'><span>QUESTLEDGER</span><b>FINANCIAL STATE</b></div><h3>Money with a mission</h3><div className='previewMoney'>KSh 50,000</div><div className='previewStats'><div><span>Unallocated</span><b>KSh 12,500</b></div><div><span>Reserved</span><b>KSh 37,500</b></div><div><span>Completed</span><b>4 quests</b></div><div><span>Spent</span><b>3 quests</b></div></div><div className='previewQuest'><span>EXAMPLE</span><b>Rent · KSh 20,000</b><strong>Funded → Deducted → History</strong></div></div></section><section className='landingFeatures'><Feature icon='💰' title='Know your money' text='Start with a general figure instead of maintaining unnecessary pseudo-bank balances.'/><Feature icon='🎯' title='Allocate with purpose' text='Move unallocated money into goals and funded recurring commitments.'/><Feature icon='✓' title='Separate achievement from spending' text='Completion is not spending. The money remains visible until it is actually spent.'/><Feature icon='🔄' title='Fund recurring reality' text='Rent, fuel, subscriptions and repayments keep their own balance and runway.'/></section><section className='landingQuote'><p>Completion tells you what you achieved. Spending tells you what happened to the money.</p><span>— The QuestLedger rule</span></section></main><footer>QuestLedger · Your financial RPG</footer></div>; }
function Feature({ icon, title, text }: { icon: string; title: string; text: string }) { return <div className='feature'><div>{icon}</div><h3>{title}</h3><p>{text}</p></div>; }

function Dashboard({ state, total, goalAllocated, open, newGoal, add, allocate, adjust }: { state: State; total: number; goalAllocated: number; open: (g: Goal) => void; newGoal: () => void; add: () => void; allocate: () => void; adjust: () => void }) {
  const h = state.recurringHealth;
  return <><section className='hero'><div><p className='eyebrow'>FINANCIAL CHARACTER</p><h1>Level {Math.max(1, Math.floor(state.xp / 500) + 1)} <em>Wealth Builder</em></h1><p className='muted'>Your money has a state. Your quests give it a mission.</p></div><div className='heroStat'><Shield /><strong>{state.stats.integrity}</strong><span>Integrity</span></div></section>
    <section className='moneyOverview'><div><span>Total money</span><strong>{money(total)}</strong></div><div><span>Unallocated</span><strong className='lime'>{money(state.unallocated)}</strong></div><div><span>Quest allocations</span><strong>{money(goalAllocated)}</strong></div></section>
    <div className='actions'><button className='primary' onClick={add}><CircleDollarSign /> Add money</button><button onClick={allocate}><Target /> Allocate</button><button onClick={newGoal}><Plus /> New quest</button><button onClick={adjust}><ArrowRightLeft /> Adjust</button></div>
    <section className='recurringHealth'><div><p className='eyebrow'>RECURRING OBLIGATIONS</p><h2>{money(h?.totalReserved || 0)} reserved</h2><p>{money(h?.monthlyOutflow || 0)} estimated monthly outflow · {h?.activeCount || 0} active commitments</p></div><div className='runwayMetric'><span>Reserved runway</span><b>{h && h.monthlyOutflow > 0 ? (h.totalReserved / h.monthlyOutflow).toFixed(1) : '0'} mo</b></div></section>
    <div className='sectionHead'><h2>Active quests</h2><button onClick={newGoal}>New <ChevronRight /></button></div>
    {state.goals.filter(g => !g.commitmentId && g.status !== 'archived').length ? <div className='grid'>{state.goals.filter(g => !g.commitmentId && g.status !== 'archived').slice(0, 4).map(g => <GoalCard key={g.id} g={g} open={open} allocate={allocate} complete={() => {}} spend={() => {}} />)}</div> : <Empty newGoal={newGoal} />}
    <section className='two'><div className='panel'><div className='panelTitle'><Wallet /> Current quest allocation</div>{state.goals.filter(g => !g.commitmentId && g.status !== 'archived').slice(0, 5).map(g => <div className='accountRow' key={g.id}><span>{g.name}</span><b>{money(g.saved)}</b></div>)}<div className='integrity'><Shield /><span>Commitments now hold their own reserved balances; period instances are history, not separate money pools.</span></div></div><div className='panel tip'><Repeat2 /><h3>Recurring runway</h3><p>Open Recurring to fund rent, fuel, loans and other repeating obligations, then see how many cycles your balance can sustain.</p></div></section></>;
}

function GoalCard({ g, open, allocate, complete, spend }: { g: Goal; open: (g: Goal) => void; allocate: () => void; complete: () => void; spend: () => void }) {
  const p = Math.min(100, g.target ? (g.saved / g.target) * 100 : 0);
  return <article className='card goalClickable' onClick={() => open(g)}><div className='tag'>{g.kind === 'expense' ? 'EXPENSE' : 'GOAL'} · {g.bucket}</div><h3>{g.name}</h3><div className='amount'>{money(g.saved)} <small>/ {money(g.target)}</small></div><div className='bar'><i style={{ width: `${p}%` }} /></div><div className='meta'><span>{g.saved >= g.target ? 'Ready' : `${money(g.target - g.saved)} remaining`}</span><span>{g.account}</span></div><div className='cardActions'><button onClick={e => { e.stopPropagation(); allocate(); }}><Plus /> Allocate</button>{g.saved >= g.target && g.status === 'active' && <button className='complete' onClick={e => { e.stopPropagation(); complete(); }}><Check /> Complete</button>}{g.saved > 0 && <button className='spend' onClick={e => { e.stopPropagation(); spend(); }}>Spent</button>}</div></article>;
}
function Goals({ goals, open, newGoal, allocate, complete, spend }: { goals: Goal[]; open: (g: Goal) => void; newGoal: () => void; allocate: (g: Goal) => void; complete: (g: Goal) => void; spend: (g: Goal) => void }) { return <><div className='pageTitle'><div><p className='eyebrow'>QUEST LOG</p><h1>Active financial quests</h1><p className='muted'>Standalone quests keep their own allocation. Recurring money lives with its commitment.</p></div><button className='primary' onClick={newGoal}><Plus /> New quest</button></div>{goals.length ? <div className='grid'>{goals.map(g => <GoalCard key={g.id} g={g} open={open} allocate={() => allocate(g)} complete={() => complete(g)} spend={() => spend(g)} />)}</div> : <Empty newGoal={newGoal} />}</>; }

function Commitments({ commitments, newCommitment, open, toggle }: { commitments: Commitment[]; newCommitment: () => void; open: (c: Commitment) => void; toggle: (c: Commitment) => void }) {
  return <><div className='pageTitle'><div><p className='eyebrow'>RECURRING</p><h1>Funded commitments</h1><p className='muted'>Each commitment owns its reserved balance and tells you how long it can sustain.</p></div><button className='primary' onClick={newCommitment}><Plus /> New commitment</button></div><div className='commitmentGrid'>{commitments.map(c => { const status = statusFor(c); return <article className='card goalClickable' key={c.id} onClick={() => open(c)}><div className='commitHead'><span className='tag'><Repeat2 /> {c.frequency}</span><button className={c.active ? 'toggleOn' : 'toggleOff'} onClick={e => { e.stopPropagation(); toggle(c); }}>{c.active ? 'Active' : 'Paused'}</button></div><h3>{c.name}</h3><div className='amount'>{money(c.balance || 0)} <small>reserved</small></div><div className='meta'><span>{cyclesText(c)}</span><span className={status === 'Underfunded' ? 'negativeText' : 'positiveText'}>{status}</span></div><div className='commitDue'><span>Next: {dateText(c.nextDueAt)}</span><span>{money(c.amount)} / {c.frequency}</span></div><div className='bar'><i style={{ width: `${Math.min(100, Number(c.amount) ? ((Number(c.balance || 0) % Number(c.amount)) / Number(c.amount)) * 100 : 0)}%` }} /></div></article>; })}</div>{!commitments.length && <div className='empty'><Repeat2 /><h3>No funded commitments</h3><p>Turn rent, fuel, loans and other repeating obligations into standing money pools.</p><button className='primary' onClick={newCommitment}>Create commitment</button></div>}</>;
}

function CommitmentDetail({ commitment, goals, events, close, openModal, edit, archive, toggle }: { commitment?: Commitment; goals: Goal[]; events: Event[]; close: () => void; openModal: (m: string) => void; edit: (c: Commitment) => void; archive: (c: Commitment) => void; toggle: (c: Commitment) => void }) {
  if (!commitment) return null;
  const c = commitment, linked = goals.filter(g => g.commitmentId === c.id).sort((a, b) => (b.periodKey || '').localeCompare(a.periodKey || '')).slice(0, 8);
  const es = events.filter(e => e.commitmentId === c.id).sort((a, b) => +new Date(b.createdAt) - +new Date(a.createdAt)).slice(0, 12);
  const remainingAfter = Math.max(0, Number(c.balance || 0) - Number(c.amount || 0));
  return <div className='overlay'><div className='modal detailModal'><div className='modalHead'><div><p className='eyebrow'>COMMITMENT</p><h2>{c.name}</h2></div><button onClick={close}><X /></button></div><div className='commitHero'><div><span className='tag'>{c.kind === 'expense' ? 'EXPENSE' : 'GOAL'} · {c.frequency}</span><div className='detailAmount'>{money(c.balance || 0)} <small>reserved</small></div><p className={statusFor(c) === 'Underfunded' ? 'negativeText' : 'positiveText'}>{statusFor(c)} · {cyclesText(c)}</p></div><div className='detailButtons'><button className='primary' onClick={() => { openModal('commitmentTopup'); }}>Top up</button><button onClick={() => { openModal('commitmentSpend'); }}>Mark spent</button></div></div><div className='metricGrid'><div><span>Recurring amount</span><b>{money(c.amount)}</b><small>{c.frequency}</small></div><div><span>Next due</span><b>{dateText(c.nextDueAt)}</b><small>{money(c.amount)} deduction</small></div><div><span>After next deduction</span><b>{money(remainingAfter)}</b><small>{remainingAfter < c.amount ? 'Underfunded next cycle' : 'Still funded'}</small></div><div><span>Projected exhaustion</span><b>{exhaustionText(c)}</b><small>if no top-up</small></div></div><div className='detailButtons manageCommit'><button onClick={() => edit(c)}>Edit</button><button onClick={() => openModal('commitmentRebalance')}><ArrowRightLeft /> Rebalance</button><button onClick={() => { openModal('commitmentAdjust'); }}><MoreHorizontal /> Adjust</button><button onClick={() => toggle(c)}>{c.active ? <Pause /> : <Play />} {c.active ? 'Pause' : 'Resume'}</button><button onClick={() => archive(c)}><Archive /> Archive</button></div><h3>Period history</h3>{linked.length ? <div className='periodList'>{linked.map(g => <div className='periodRow' key={g.id}><div><b>{g.periodKey}</b><small>{g.periodStatus || g.status}</small></div><strong>{g.spent ? money(g.spent) : money(g.target)}</strong></div>)}</div> : <p className='muted'>No periods recorded yet.</p>}<h3>Activity</h3>{es.length ? <div className='timeline'>{es.map(e => <div className='timelineItem' key={e.id}><div className={`eventDot ${e.type.includes('deduction') || e.type.includes('spend') ? 'negative' : 'positive'}`} /><div className='eventBody'><div><b>{e.type.replaceAll('_', ' ')}</b><strong>{e.amount ? money(e.amount) : ''}</strong></div><small>{new Date(e.createdAt).toLocaleString()}{e.reason ? ' · ' + e.reason : ''}</small></div></div>)}</div> : <p className='muted'>No activity yet.</p>}</div></div>;
}

function Archives({ goals, commitments, open }: { goals: Goal[]; commitments: Commitment[]; open: (g: Goal) => void }) { return <><div className='pageTitle'><div><p className='eyebrow'>HISTORY</p><h1>Archives</h1><p className='muted'>Finished quests and archived commitments remain visible as history.</p></div></div>{goals.length ? <div className='grid'>{goals.map(g => <article className='card goalClickable' key={g.id} onClick={() => open(g)}><div className='tag'><Archive /> ARCHIVED QUEST</div><h3>{g.name}</h3><div className='amount'>{money(g.spent)} <small>spent</small></div><div className='meta'><span>{g.kind === 'expense' ? 'Expense' : 'Goal'}</span><span>{g.periodKey || g.deadline || 'Completed'}</span></div></article>)}</div> : null}{commitments.length ? <><div className='sectionHead'><h2>Archived commitments</h2></div><div className='commitmentGrid'>{commitments.map(c => <article className='card' key={c.id}><div className='tag'><Archive /> ARCHIVED COMMITMENT</div><h3>{c.name}</h3><div className='amount'>{money(c.balance || 0)} <small>remaining</small></div><div className='meta'><span>{c.frequency}</span><span>{c.bucket}</span></div></article>)}</div></> : null}{!goals.length && !commitments.length && <div className='empty'><Archive /><h3>Your archive is empty</h3><p>Completed and archived financial history will appear here.</p></div>}</>; }

function GoalDetail({ goal, events, close, edit, adjustTarget, archive, allocate, spend }: { goal?: Goal; events: Event[]; close: () => void; edit: (g: Goal) => void; adjustTarget: (g: Goal) => void; archive: (g: Goal) => void; allocate: (g: Goal) => void; spend: (g: Goal) => void }) {
  if (!goal) return null;
  const es = events.filter(e => e.goalId === goal.id || e.from === goal.id || e.to === goal.id).sort((a, b) => +new Date(b.createdAt) - +new Date(a.createdAt));
  return <div className='overlay'><div className='modal detailModal'><div className='modalHead'><div><p className='eyebrow'>QUEST HISTORY</p><h2>{goal.name}</h2></div><button onClick={close}><X /></button></div><div className='detailHero'><div><span className='tag'>{goal.kind === 'expense' ? 'EXPENSE' : 'GOAL'} · {goal.bucket}</span><div className='detailAmount'>{money(goal.saved)} <small>remaining allocation</small></div><p className='muted'>{goal.status === 'archived' ? 'Archived' : goal.status === 'completed' ? 'Completed' : 'Active'} · {money(goal.spent)} spent</p></div><div className='detailButtons'><button onClick={() => edit(goal)}>Edit</button><button onClick={() => adjustTarget(goal)}>Target</button><button className='primary' onClick={() => allocate(goal)} disabled={goal.status === 'archived'}><Plus /> Allocate</button>{goal.saved > 0 && <button className='spend' onClick={() => spend(goal)}>Mark spent</button>}{goal.status !== 'archived' && <button onClick={() => archive(goal)}><Archive /> Archive</button>}</div></div><h3>Activity</h3>{es.length ? <div className='timeline'>{es.map(e => <div className='timelineItem' key={e.id}><div className={`eventDot ${e.amount >= 0 ? 'positive' : 'negative'}`} /><div className='eventBody'><div><b>{e.type.replaceAll('_', ' ')}</b><strong>{e.amount ? money(e.amount) : ''}</strong></div><small>{new Date(e.createdAt).toLocaleString()}{e.reason ? ' · ' + e.reason : ''}</small></div></div>)}</div> : <p className='muted'>No activity yet.</p>}</div></div>;
}

function Empty({ newGoal }: { newGoal: () => void }) { return <div className='empty'><Target /><h3>No active quests</h3><p>Give a goal or expense a mission.</p><button className='primary' onClick={newGoal}>Create quest</button></div>; }
function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className='overlay'><div className='modal'><div className='modalHead'><h2>{title}</h2><button onClick={close}><X /></button></div>{children}</div></div>; }

function Form({ modal, form, setForm, state, submit, busy }: { modal: string; form: Record<string, string>; setForm: (v: Record<string, string>) => void; state: State; submit: (v?: Record<string, string>) => void; busy: boolean }) {
  const f = (k: string, l: string, t = 'text') => <label>{l}<input type={t} min={t === 'number' ? '0.01' : undefined} step={t === 'number' ? '0.01' : undefined} value={form[k] || ''} onChange={e => setForm({ ...form, [k]: e.target.value })} /></label>;
  const buckets = state.buckets.map(b => <option key={b.id} value={b.name}>{b.name}</option>), accounts = state.accounts.map(a => <option key={a.id} value={a.name}>{a.name}</option>);
  if (modal === 'money') return <>{f('amount', 'Amount to add', 'number')}{f('location', 'Where is it?')}<p className='formHint'>This increases unallocated money. The location is context, not a separate bank balance.</p><button className='primary full' disabled={!form.amount || Number(form.amount) <= 0 || busy} onClick={() => submit()}>Add {form.amount ? money(Number(form.amount)) : 'money'}</button></>;
  if (modal === 'goal') return <>{f('name', 'Quest name')}{f('target', 'Target amount', 'number')}<div className='formgrid'><label>Type<select value={form.kind || 'goal'} onChange={e => setForm({ ...form, kind: e.target.value })}><option value='goal'>Goal — money remains mine</option><option value='expense'>Expense — expected to be spent</option></select></label><label>Bucket<select value={form.bucket || ''} onChange={e => setForm({ ...form, bucket: e.target.value })}><option value=''>Choose bucket</option>{buckets}</select></label><label>Location<select value={form.account || ''} onChange={e => setForm({ ...form, account: e.target.value })}><option value=''>Optional location</option>{accounts}</select></label></div>{f('deadline', 'Deadline', 'date')}<button className='primary full' disabled={!form.name || !form.target || !form.bucket || busy} onClick={() => submit()}>Create quest</button></>;
  if (modal === 'contribute') return <>{!form.goalId && <label>Quest<select value={form.goalId || ''} onChange={e => setForm({ ...form, goalId: e.target.value })}><option value=''>Choose quest</option>{state.goals.filter(g => !g.commitmentId && g.status === 'active').map(g => <option key={g.id} value={g.id}>{g.name}</option>)}</select></label>}<div className='available'><span>Unallocated</span><b>{money(state.unallocated)}</b></div>{f('amount', 'Amount to allocate', 'number')}<button className='primary full' disabled={!form.goalId || !form.amount || Number(form.amount) <= 0 || Number(form.amount) > state.unallocated || busy} onClick={() => submit()}>Allocate money</button></>;
  if (modal === 'spend') return <><div className='available'><span>Available allocation</span><b>{money(form.goalId ? state.goals.find(g => g.id === form.goalId)?.saved || 0 : 0)}</b></div>{f('amount', 'Amount spent', 'number')}{f('reason', 'What was it for?')}<p className='formHint'>Spending reduces the allocation and records money leaving your possession.</p><button className='primary full' disabled={!form.goalId || !form.amount || Number(form.amount) <= 0 || busy} onClick={() => submit()}>Mark spent</button></>;
  if (modal === 'commitment') return <>{f('name', 'Commitment name')}{f('amount', 'Recurring amount', 'number')}<div className='formgrid'><label>Frequency<select value={form.frequency || 'monthly'} onChange={e => setForm({ ...form, frequency: e.target.value })}><option value='daily'>Daily</option><option value='weekly'>Weekly</option><option value='monthly'>Monthly</option><option value='yearly'>Yearly</option></select></label><label>Type<select value={form.kind || 'expense'} onChange={e => setForm({ ...form, kind: e.target.value })}><option value='expense'>Expense</option><option value='goal'>Goal</option></select></label><label>Bucket<select value={form.bucket || ''} onChange={e => setForm({ ...form, bucket: e.target.value })}><option value=''>Choose bucket</option>{buckets}</select></label><label>Location<select value={form.account || ''} onChange={e => setForm({ ...form, account: e.target.value })}><option value=''>Optional location</option>{accounts}</select></label></div>{['monthly','yearly'].includes(form.frequency || 'monthly') && f('dueDay', 'Due day of month', 'number')}<button className='primary full' disabled={!form.name || !form.amount || !form.frequency || !form.bucket || busy} onClick={() => submit()}>Create funded commitment</button></>;
  if (modal === 'goalEdit') return <>{f('name', 'Quest name')}<div className='formgrid'><label>Type<select value={form.kind || 'goal'} onChange={e => setForm({ ...form, kind: e.target.value })}><option value='goal'>Goal</option><option value='expense'>Expense</option></select></label><label>Bucket<select value={form.bucket || ''} onChange={e => setForm({ ...form, bucket: e.target.value })}><option value=''>Choose bucket</option>{buckets}</select></label><label>Location<select value={form.account || ''} onChange={e => setForm({ ...form, account: e.target.value })}><option value=''>Optional location</option>{accounts}</select></label></div>{f('deadline', 'Deadline', 'date')}<p className='formHint'>This changes the quest details only. Money already allocated stays allocated.</p><button className='primary full' disabled={!form.name || !form.bucket || busy} onClick={() => submit()}>Save quest</button></>;
  if (modal === 'goalTarget') return <>{f('target', 'New target', 'number')}<p className='formHint'>Increasing the target leaves allocated money untouched. If the new target is below the current allocation, choose where the released money should go.</p>{Number(form.target || 0) < Number(state.goals.find(g => g.id === form.id)?.saved || 0) && <label>Release excess to<select value={form.releaseTo || 'unallocated'} onChange={e => setForm({ ...form, releaseTo: e.target.value })}><option value='unallocated'>Unallocated money</option>{state.goals.filter(g => !g.commitmentId && g.id !== form.id && g.status !== 'archived').map(g => <option key={g.id} value={g.id}>{g.name}</option>)}</select></label>}<button className='primary full' disabled={!form.target || Number(form.target) <= 0 || busy} onClick={() => submit()}>Save target</button></>;
  if (modal === 'goalArchive') { const g = state.goals.find(x => x.id === form.id); return <>{g && g.saved > 0 ? <><p className='formHint'>This quest still holds {money(g.saved)}. Nothing is deleted: choose where the allocation goes before archiving.</p><label>Move remaining allocation to<select value={form.releaseTo || 'unallocated'} onChange={e => setForm({ ...form, releaseTo: e.target.value })}><option value='unallocated'>Unallocated money</option>{state.goals.filter(x => !x.commitmentId && x.id !== g.id && x.status !== 'archived').map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label></> : <p className='formHint'>This quest has no remaining allocation. Its history will stay in Archives.</p>}<button className='primary full' disabled={busy} onClick={() => submit()}>Archive quest</button></>;
  }
  if (modal === 'commitmentEdit') return <>{f('name', 'Commitment name')}<div className='formgrid'><label>Type<select value={form.kind || 'expense'} onChange={e => setForm({ ...form, kind: e.target.value })}><option value='expense'>Expense</option><option value='goal'>Goal</option></select></label><label>Bucket<select value={form.bucket || ''} onChange={e => setForm({ ...form, bucket: e.target.value })}><option value=''>Choose bucket</option>{buckets}</select></label><label>Location<select value={form.account || ''} onChange={e => setForm({ ...form, account: e.target.value })}><option value=''>Optional location</option>{accounts}</select></label></div><p className='formHint'>This edits commitment details only. Use Adjust for amount or frequency changes that begin next cycle.</p><button className='primary full' disabled={!form.name || !form.bucket || busy} onClick={() => submit()}>Save commitment</button></>;
  if (modal === 'commitmentArchive') return <><p className='formHint'>Archiving stops future deductions and preserves the commitment's history. Any reserved balance must be rebalanced first.</p><button className='primary full' disabled={busy || Number(state.commitments.find(c => c.id === form.commitmentId)?.balance || 0) > 0} onClick={() => submit()}>Archive commitment</button></>;
  if (modal === 'commitmentTopup') return <><div className='available'><span>Unallocated</span><b>{money(state.unallocated)}</b></div>{f('amount', 'Top-up amount', 'number')}<button className='primary full' disabled={!form.amount || Number(form.amount) <= 0 || Number(form.amount) > state.unallocated || busy} onClick={() => submit()}>Reserve money</button></>;
  if (modal === 'commitmentSpend') return <>{f('amount', 'Amount spent', 'number')}{f('reason', 'What was it for?')}<button className='primary full' disabled={!form.amount || Number(form.amount) <= 0 || busy} onClick={() => submit()}>Mark spent</button></>;
  if (modal === 'commitmentRebalance') return <>{f('amount', 'Amount to move', 'number')}<label>Destination<select value={form.to || 'unallocated'} onChange={e => setForm({ ...form, to: e.target.value })}><option value='unallocated'>Back to unallocated</option>{state.commitments.filter(c => c.id !== form.commitmentId && !c.archived).map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{f('reason', 'Reason')}<button className='primary full' disabled={!form.amount || Number(form.amount) <= 0 || busy} onClick={() => submit()}>Rebalance</button></>;
  if (modal === 'commitmentAdjust') return <>{f('amount', 'New recurring amount', 'number')}<label>New frequency<select value={form.frequency || ''} onChange={e => setForm({ ...form, frequency: e.target.value })}><option value=''>Keep current frequency</option><option value='daily'>Daily</option><option value='weekly'>Weekly</option><option value='monthly'>Monthly</option><option value='yearly'>Yearly</option></select></label><p className='formHint'>Changes take effect on the next cycle.</p><button className='primary full' disabled={(!form.amount && !form.frequency) || busy} onClick={() => submit()}>Save next-cycle changes</button></>;
  if (modal === 'rebalance') return <><p className='muted'>Move an allocation between standalone quests, record an expense, or remove an allocation from tracking.</p><label>What happened?<select value={form.kind || 'transfer'} onChange={e => setForm({ ...form, kind: e.target.value })}><option value='transfer'>Move to another quest</option><option value='expense'>Record an expense</option><option value='withdrawal'>Remove from tracking</option></select></label><label>Source quest<select value={form.from || ''} onChange={e => setForm({ ...form, from: e.target.value })}><option value=''>Choose quest</option>{state.goals.filter(g => !g.commitmentId && g.status !== 'archived').map(g => <option key={g.id} value={g.id}>{g.name}</option>)}</select></label>{(form.kind || 'transfer') === 'transfer' && <label>Destination quest<select value={form.to || ''} onChange={e => setForm({ ...form, to: e.target.value })}><option value=''>Choose quest</option>{state.goals.filter(g => !g.commitmentId && g.status !== 'archived').map(g => <option key={g.id} value={g.id}>{g.name}</option>)}</select></label>}{f('amount', 'Amount', 'number')}{f('reason', 'Description')}<button className='primary full' disabled={!form.from || !form.amount || ((form.kind || 'transfer') === 'transfer' && !form.to) || busy} onClick={() => submit()}>Record adjustment</button></>;
  return <>{f('name', modal === 'account' ? 'Account/location name' : 'Bucket name')}<button className='primary full' disabled={!form.name || busy} onClick={() => submit(form)}>Add</button></>;
}

function Character({ state }: { state: State }) { const stats = [['Integrity', state.stats.integrity], ['Discipline', state.stats.discipline], ['Consistency', state.stats.consistency], ['Balance', state.stats.balance], ['Power', state.stats.power], ['Adaptability', state.stats.adaptability]]; return <><div className='pageTitle'><div><p className='eyebrow'>CHARACTER SHEET</p><h1>Your financial character</h1></div></div><div className='statsGrid'>{stats.map(([n, v]) => <div className='statCard' key={n}><Shield /><span>{n}</span><strong>{v}</strong><div className='bar'><i style={{ width: `${v}%` }} /></div></div>)}</div></>; }
function Analytics({ state, addBucket, addAccount }: { state: State; addBucket: () => void; addAccount: () => void }) { const h = state.recurringHealth; return <><div className='pageTitle'><div><p className='eyebrow'>SYSTEM VIEW</p><h1>Money architecture</h1><p className='muted'>See the distinction between unallocated money, quest allocations and recurring reserves.</p></div></div><div className='statsGrid'><div className='statCard'><Wallet /><span>Unallocated</span><strong>{money(state.unallocated)}</strong></div><div className='statCard'><Repeat2 /><span>Recurring reserved</span><strong>{money(h?.totalReserved || 0)}</strong></div><div className='statCard'><CalendarDays /><span>Monthly recurring outflow</span><strong>{money(h?.monthlyOutflow || 0)}</strong></div></div><div className='panel analysisRow'><h3>Money locations</h3>{state.accounts.map(a => <div className='accountRow' key={a.id}><span>{a.name}</span><small>context only</small></div>)}<div className='manageRow'><button onClick={addAccount}>Add account</button><button onClick={addBucket}>Add bucket</button></div></div></>; }
